### ISSUE TITLE
non-required null TokenID will cause exception and rendering failure 

### ISSUE THREAD

**Issue by fuzzyducky** [JeffDarchuk/SCTokenManager#20]
If I set up an ViewAutoToken with a TokenID in the model class with required set to false, I get an error on render if I don't select an item for that TokenID.

16132 17:12:03 ERROR unable to expand tokens for item {DAF777C8-50A3-4860-9143-D1B875F71349}
Exception: System.ArgumentNullException
Message: Value cannot be null.
Parameter name: g
Source: mscorlib
   at System.Guid..ctor(String g)
   at Sitecore.Data.ID..ctor(String id)
   at TokenManager.Data.TokenDataTypes.Attributes.TokenIdAttribute.GetObject(TokenDataCollection collection, String name, Type t)
   at TokenManager.Data.Tokens.ModelAutoToken`1.GenerateModel(TokenDataCollection extraData)
   at TokenManager.Data.Tokens.ModelAutoToken`1.Value(TokenDataCollection extraData)
   at TokenManager.Management.DefaultTokenKeeperService.ParseTokenValueFromTokenIdentifier(String token, Item item)
   at TokenManager.Management.DefaultTokenKeeperService.ReplaceRTETokens(RenderFieldArgs args, String text)

The issue is https://github.com/JeffDarchuk/SCTokenManager/blob/4a132b51d5cad6bec6a15b009540799be4dfedfe/Source/TokenManager/Data/TokenDataTypes/Attributes/TokenIdAttribute.cs#L45

null is getting passed into the ID() constructor

**Comment by JeffDarchuk** [comment]
Hey Fuzzyducky (awesome name btw)
Thanks for submitting this bug, it's fixed in 2.5.6 which is available now.
