### ISSUE TITLE
Error when deleting the TokenManager root item

### ISSUE THREAD

**Issue by kamsar** [JeffDarchuk/SCTokenManager#6]
I went to delete /sitecore/content/TokenManager (nope not uninstalling) on 8.1U1 and got the following exception:

```
17944 12:14:40 ERROR One or more exceptions occurred while processing the subscribers to the 'item:deleting' event.
Exception[1]: System.InvalidOperationException 
Message[1]: Attempt to retrieve context object of type 'Sitecore.Mvc.Presentation.PageContext' from empty stack. 
Source[1]: Sitecore.Mvc 
   at Sitecore.Mvc.Common.ContextService.Peek[T]()
   at Sitecore.Mvc.Pipelines.Response.RenderRendering.ResolveArea.Process(RenderRenderingArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
   at Sitecore.Mvc.Helpers.SitecoreHelper.RenderRendering(Rendering rendering)
   at TokenManager.Data.Tokens.RenderingToken.Value(NameValueCollection extraData)
   at TokenManager.Handlers.TokenOperations.TokenUnzipper.ProcessRte(Field field, Object ret, Boolean preview)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at TokenManager.Handlers.TokenOperations.TokenUnzipper.Unzip(Boolean preview)
   at TokenManager.Pipelines.Deleting.TokenDeleting.OnItemDeleting(Object sender, EventArgs e)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) 
```

My guess is that the rendering token that's being removed doesn't like running on a background thread? Looks like 8.1U1 may invoke all event handlers in parallel since it's now throwing an aggregate exception.

**Comment by JeffDarchuk** [comment]
this is fixed in TM 2.0.0
